# Generated by Django 5.2.3 on 2025-06-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('salary', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=175)),
                ('email', models.EmailField(max_length=254)),
                ('telf', models.CharField(max_length=12)),
                ('puesto', models.TextField()),
                ('esJefe', models.BooleanField()),
                ('esContable', models.BooleanField()),
                ('esComercial', models.BooleanField()),
            ],
        ),
    ]
