# Generated by Django 5.2.3 on 2025-06-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pvp', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
