# Generated by Django 5.2.3 on 2025-06-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='electronics', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='check with the manufacturer', max_length=200),
        ),
    ]
