# Generated by Django 5.2.3 on 2025-06-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_cita', models.DateField()),
                ('tipo_cita', models.CharField(choices=[('seguridad', 'Auditoría de ciberseguridad'), ('presupuesto', 'Presupuesto empresarial')], max_length=20)),
                ('comentario', models.TextField(max_length=300)),
            ],
        ),
    ]
